### ISSUE TITLE
Error in jsonschema.py module when generating a new app

### ISSUE THREAD

**Issue by aalhour** [guokr/swagger-py-codegen#103]
Hi,

I am trying to generate a web application from a swagger specification and I get the following error, I have already validated my swagger specification on the Online Swagger Editor.

```
$ swagger_py_codegen -s swagger.yaml example-app -p demo --ui --spec

......................................generate    example-app/demo/static/swagger-ui
Traceback (most recent call last):
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/bin/swagger_py_codegen", line 11, in <module>
    load_entry_point('swagger-py-codegen==0.2.9', 'console_scripts', 'swagger_py_codegen')()
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/lib/python3.6/site-packages/swagger_py_codegen/command.py", line 121, in generate
    for code in generator.generate():
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/lib/python3.6/site-packages/swagger_py_codegen/base.py", line 44, in generate
    for code in g:
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/lib/python3.6/site-packages/swagger_py_codegen/base.py", line 47, in generate
    for code in self._process():
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/lib/python3.6/site-packages/swagger_py_codegen/jsonschema.py", line 109, in _process
    yield Schema(build_data(self.swagger))
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/lib/python3.6/site-packages/swagger_py_codegen/jsonschema.py", line 71, in build_data
    validator = dict(_parameters_to_schemas(path_param + method_param))
  File "/Users/ahmad/Projects/Work/swagger_code_gen/venv/lib/python3.6/site-packages/swagger_py_codegen/jsonschema.py", line 28, in _parameters_to_schemas
    yield location, param['schema']
KeyError: 'schema'
```

The error occurs on both Python2.7 and Python3.6.

Any ideas why this happens and how can I resolve it?

**Comment by aalhour** [comment]
Solved the issue in the end by adding a `schema` attribute to all URL properties including the ones that have a simple data type like `integer` and `string`.

Don't you guys think this addition is unnecessary? I mean a parameter that has a type set to `integer` doesn't really need an additional `schema` attribute with a type set to `integer` as well.

**Comment by foodszhang** [comment]
Swagger2.0 made `schema` necessary  when describing request body,. See this https://swagger.io/docs/specification/2-0/describing-request-body/.
