### ISSUE TITLE
 unexpected keyword argument 'spec'

### ISSUE THREAD

**Issue by steptian** [guokr/swagger-py-codegen#127]
TypeError: generate() got an unexpected keyword argument 'spec'
the full trace as follow:

swagger_py_codegen -s api.yml example-app -p demo -tlp=sanic
Traceback (most recent call last):
  File "/usr/local/bin/swagger_py_codegen", line 11, in <module>
    sys.exit(generate())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
TypeError: generate() got an unexpected keyword argument 'spec'

**Comment by zrq495** [comment]
pip install 'click<=6.7'

**Comment by steptian** [comment]
new question:
swagger_py_codegen -s api.yaml example-app -p demo -tlp=sanic
Traceback (most recent call last):
  File "/usr/local/bin/swagger_py_codegen", line 11, in <module>
    sys.exit(generate())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 695, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 675, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 868, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 513, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/swagger_py_codegen/command.py", line 151, in generate
    source = template.render_code(code)
  File "/usr/local/lib/python3.5/site-packages/swagger_py_codegen/base.py", line 67, in render_code
    return self.render(code.template, **code.data)
  File "/usr/local/lib/python3.5/site-packages/swagger_py_codegen/base.py", line 63, in render
    return template.render(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 706, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 515, in handle_exception
    raise exc_value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/swagger_py_codegen/templates/sanic/schemas.tpl", line 10, in <module>
    {% for name, value in schemas.items() %}
  File "/usr/local/lib/python3.5/site-packages/jinja2/environment.py", line 353, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: b"'schemas' is undefined"

**Comment by steptian** [comment]
commented the code in   "/usr/local/lib/python3.5/site-packages/swagger_py_codegen/templates/sanic/schemas.tpl"
about schemas, problem solved.
