### ISSUE TITLE
name "RefResolver" is not defined

### ISSUE THREAD

**Issue by ybbiubiubiu** [guokr/swagger-py-codegen#132]
I get a unkown probleme. :

Traceback (most recent call last):
  File "/Users/yangbin/Desktop/swagger-py-codegen/example-app/demo/__init__.py", line 8, in <module>
    import v1
  File "/Users/yangbin/Desktop/swagger-py-codegen/example-app/demo/v1/__init__.py", line 6, in <module>
    from .routes import routes
  File "/Users/yangbin/Desktop/swagger-py-codegen/example-app/demo/v1/routes.py", line 11, in <module>
    from .api.pets import Pets
  File "/Users/yangbin/Desktop/swagger-py-codegen/example-app/demo/v1/api/__init__.py", line 8, in <module>
    from ..validators import request_validate, response_filter
  File "/Users/yangbin/Desktop/swagger-py-codegen/example-app/demo/v1/validators.py", line 24, in <module>
    from .schemas import (
  File "/Users/yangbin/Desktop/swagger-py-codegen/example-app/demo/v1/schemas.py", line 31, in <module>
    resolver = RefResolver.from_schema(definitions)
NameError: name 'RefResolver' is not defined..

please tell me how i can solve this?

**Comment by KevinTao511** [comment]
have you solve it? I have the same problem

**Comment by ybbiubiubiu** [comment]
> have you solve it? I have the same problem

nope
