### ISSUE TITLE
The browser (or proxy) sent a request that this server could not understand

### ISSUE THREAD

**Issue by snakecy** [guokr/swagger-py-codegen#140]
when input array with ctrl inside, like:
![image](https://user-images.githubusercontent.com/12490881/58545046-0cbb7480-8235-11e9-96d1-f3ff6569e851.png)

the error turns out to be :
![image](https://user-images.githubusercontent.com/12490881/58545134-3b394f80-8235-11e9-8f13-21957027225a.png)

how to deal with it ?

**Comment by Weilor** [comment]
The reason is about json format, you can not change line in a string which is a member of list.
```python
>>> json.loads('{\n  "sku_id": "123",\n  "user_id": [\n    "aaaassssddd"\n  ]\n}')
{'sku_id': '123', 'user_id': ['aaaassssddd']}
>>> json.loads('{\n  "sku_id": "123",\n  "user_id": [\n    "aaaas\nsssddd"\n  ]\n}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hsw/.pyenv/versions/3.6.0/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/home/hsw/.pyenv/versions/3.6.0/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/hsw/.pyenv/versions/3.6.0/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 4 column 11 (char 46)
```
So if you want to pass a string contain control character, use double slash like this
```python
>>> json.loads('{\n  "sku_id": "123",\n  "user_id": [\n    "aaaas\\nsssddd"\n  ]\n}')
{'sku_id': '123', 'user_id': ['aaaas\nsssddd']}
```
