### ISSUE TITLE
conversion failed

### ISSUE THREAD

**Issue by totaluserkksssssks** [guokr/swagger-py-codegen#141]
Hello, tried to convert this:
https://jdegre.github.io/5GC_APIs/editor/?url=https://raw.githubusercontent.com/jdegre/5GC_APIs/master/TS29122_NIDD.yaml

`swagger_py_codegen --swagger-doc openapi.yaml appdir2
No handlers could be found for logger "jsonspec.pointer.bases"
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/swagger_py_codegen", line 11, in <module>
    sys.exit(generate())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/swagger_py_codegen/command.py", line 177, in generate
    swagger = Swagger(data)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/swagger_py_codegen/parser.py", line 65, in __init__
    self._process_ref()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/swagger_py_codegen/parser.py", line 72, in _process_ref
    data = resolve(self.data, ref)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/jsonspec/reference/__init__.py", line 62, in resolve
    return registry.resolve(local)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/jsonspec/reference/bases.py", line 48, in resolve
    obj = token.extract(obj, bypass_ref=True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/jsonspec/pointer/bases.py", line 223, in extract
    obj = self.extract_mapping(obj)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/jsonspec/pointer/bases.py", line 251, in extract_mapping
    raise OutOfBounds(obj, 'member {!r} not found'.format(str(self)))
jsonspec.pointer.exceptions.OutOfBounds: "member 'responses' not found"
`

But unfortunately this does not work, could you help me, please?

**Comment by Weilor** [comment]
Sorry for replying you so late. But according to your information I think this is because one path defined in your yaml file did not conclude a response definition. If have any other question please contact us again.
