### ISSUE TITLE
Run the codegen in python3.4 and python2.7 error occurs

### ISSUE THREAD

**Issue by LouisZou** [guokr/swagger-py-codegen#36]
I pull the swagger_py_codegen and run it in python3 like the following:
Pip install swagger_py_codegen
Swagger_py_codegen

There is the following error message:
Traceback (most recent call last):
  File "/scratch/lozou/MyProject/Python/py34env/bin/swagger_py_codegen", line 11, in <module>
    sys.exit(generate())
  File "/scratch/lozou/MyProject/Python/py34env/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/scratch/lozou/MyProject/Python/py34env/lib/python3.4/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/scratch/lozou/MyProject/Python/py34env/lib/python3.4/site-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    if locale.lower().endswith(('.utf-8', '.utf8')):
TypeError: 'str' does not support the buffer interface
(

And if I run it in python2.6, it also failed:
Traceback (most recent call last):
  File "/scratch/lozou/MyProject/Python/py26env/bin/swagger_py_codegen", line 7, in <module>
    from swagger_py_codegen import generate
  File "/scratch/lozou/MyProject/Python/py26env/lib/python2.6/site-packages/swagger_py_codegen/__init__.py", line 1, in <module>
    from .command import generate
  File "/scratch/lozou/MyProject/Python/py26env/lib/python2.6/site-packages/swagger_py_codegen/command.py", line 12, in <module>
    from .flask import FlaskGenerator
  File "/scratch/lozou/MyProject/Python/py26env/lib/python2.6/site-packages/swagger_py_codegen/flask.py", line 134
    locations = {_location(loc): val for loc, val in v.iteritems()}
                                       ^
SyntaxError: invalid syntax

any configuration and package needed?

**Comment by LouisZou** [comment]
I re-install the virtual for python2.7 ,now it is ok. I can run the codegen to genetrate Flask server code.
