### ISSUE TITLE
incorrect "ValueError: $ref circular references found!" in parser

### ISSUE THREAD

**Issue by debdude** [guokr/swagger-py-codegen#57]
Given two files, 

testing.yml

```
swagger: '2.0'
info:
  version: "0.1.1"
  title: test Application

paths:
  /account:
    get:
      responses:
        '200':
          description: the status of an account
          schema:
            properties:
              account:
                $ref: '#/definitions/Account'

definitions:
  $ref: 'testdef.yml'
```

and testdef.yml:

```
Account:
  type: object
  required:
    - emailAddress
  properties:
    emailAddress:
      type: string
    installationInformation:
      $ref: '#/InstallationInformation'


InstallationInformation:
  description: A collection of information that describes an instance of the application and what device it is running on.
  properties:
    OSType:
      type: string
      description:
        Android or Apple or other

```

They validate ok:

```
schemas$ swagger validate testing.yml 
testing.yml is valid
```

but swagger_py_codegen stumbles on $refs:

```
$ swagger_py_codegen  --swagger-doc schemas/testing.yml -p api app --ui --spec
Traceback (most recent call last):
  File "/home/d/venv/tm/bin/swagger_py_codegen", line 11, in <module>
    sys.exit(generate())
  File "/home/d/venv/tm/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/d/venv/tm/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/d/venv/tm/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/d/venv/tm/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/d/venv/tm/local/lib/python2.7/site-packages/swagger_py_codegen/command.py", line 77, in generate
    swagger = Swagger(data)
  File "/home/d/venv/tm/local/lib/python2.7/site-packages/swagger_py_codegen/parser.py", line 29, in __init__
    self._references_sort()
  File "/home/d/venv/tm/local/lib/python2.7/site-packages/swagger_py_codegen/parser.py", line 67, in _references_sort
    raise ValueError(msg)
ValueError: $ref circular references found!

```

**Comment by SimplicityGuy** [comment]
Indeed, this is a problem. Other codegen tools support circular references. See https://github.com/swagger-api/swagger-codegen/issues/728.

I his this issue with the following yml:
```yaml
Node:
    description: Generic node.
    type: object
    properties:
      type:
        description: Type or label of the node.
        type: string
      properties:
        description: Node specific dictionary of key/value pairs.
        type: object
        additionalProperties:
          type: string
      relationships:
        descriptions: Relationships this node has with other nodes.
        type: array
        items:
          $ref: '#/definitions/Relationship'
  Relationship:
    description: Relationship that one node has with another.
    type: object
    properties:
      type:
        description: Type of relationship between nodes.
        type: string
      properties:
        description: Relationship specific dictionary of key/value pairs.
        type: object
        additionalProperties:
          type: string
      node:
        $ref: '#/definitions/Node'
```

**Comment by SimplicityGuy** [comment]
There is a test case ```test_swagger_ref_count_04``` that I believe is erroneous. There is nothing in the Swagger spec that disallows nested definitions or definitions that refer back onto themselves.

**Comment by ciacicode** [comment]
Got the same problem here. Is there a way I can get past this while it's getting fixed?

**Comment by RakiP** [comment]
this problem still persists

**Comment by gusibi** [comment]
@debdude 
this problem fixed

but need to modify the testdef.yml file

```
$ref: '#/InstallationInformation' ->  $ref: '#/definitions/InstallationInformation'
```
