### ISSUE TITLE
FlaskValidatorAdaptor crashes on validating an invalid integer in query string

### ISSUE THREAD

**Issue by eht16** [guokr/swagger-py-codegen#83]
In a service spec I defined a query string parameter as integer like:
```yaml
[...]
      parameters:
        - name: offset
          in: query
          required: false
          type: integer
[...]
```

When I pass an invalid value like `abc` for the offset parameter, the validating code gets a `ValueError` which is not handled:

```
Traceback (most recent call last):
  File "/home/.../controller.py", line 115, in __call__
    self._validate_request()
  File "/home/.../controller.py", line 248, in _validate_request
    wrapped_callable()
  File "/home/.../api_v1/validators.py", line 94, in wrapper
    result, errors = validator.validate(value)
  File "/home/.../api_v1/validators.py", line 72, in validate
    value = self.type_convert(value)
  File "/home/.../api_v1/validators.py", line 68, in type_convert
    result[k] = fun(values)
  File "/home/.../api_v1/validators.py", line 49, in <lambda>
    'integer': lambda v: int(v[0]),
ValueError: invalid literal for int() with base 10: 'abc'
```

Maybe we need a bit more code for the `integer` and `float` types in `convert_funs` which checks for `ValueError` and treat such an error as an invalid value.

Using: swagger-py-codegen==0.2.3

**Comment by jizhouli** [comment]
thanks @eht16 ,this PR have been merged in #84 . ValueError exception will raise when an invalid query parameter is passed in, thanks for your contribution.
